### ISSUE TITLE
Permission Denied - Can't mount NFS

### ISSUE THREAD

**Issue by luklewluk** [MDobak/docker-symfony#1]
Hi. I tried to use your setup on my Mac OS 10.12.6.

I cloned the repository and executed:
` ./console create-project symfony/website-skeleton 4.*`

Output:
```
WARNING: The WEB_PATH variable is not set. Defaulting to a blank string.
symfony_db is up-to-date
Creating symfony_php ... error

ERROR: for symfony_php  Cannot create container for service php: error while mounting volume with options: type='nfs' device=':/Users/myuser/Sites/docker-symfony/docker/../app' o='addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3': permission denied

ERROR: for php  Cannot create container for service php: error while mounting volume with options: type='nfs' device=':/Users/myuser/Sites/docker-symfony/docker/../app' o='addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3': permission denied
ERROR: Encountered errors while bringing up the project.
```

How can I resolve it? I tried to change user and group IDs to:
```
APP_USER_ID=501
APP_GROUP_ID=20
```
But it's not the way to make it working because I was getting the following error:
```
addgroup: gid '20' in use
```

**Comment by luklewluk** [comment]
Never mind. I had a conflicting row in `/etc/exports` 🙈

**Comment by MDobak** [comment]
I am glad that you have solved your problem ;) On MacOS, there is a commend`nfsd checkexports` which could help to detect it earlier. Maybe it should be called with the method `setup_macos_nfs`.
